export const TOUCHABLE_AREA_TO_START_RESIZING_IN_PIXELS = 4;

export const LAST_SYSTEM_ESSENTIAL_PID = 1; // systemd

export const INITIAL_PROCESS_WINDOW_HIGHEST_ZINDEX = 0;

export const INITIAL_SYSTEM_LAYOUT_STYLE_CLASS = 'row__style';

export const INITIAL_SYSTEM_THEME_STYLE_CLASS = 'orange';