export const TOUCHABLE_AREA_TO_START_RESIZING_IN_PIXELS = 5;

export const LIMIT_TO_CHANGE_INITIAL_PROCESS_WINDOW_DIMENSION_PERCENTAGE_IN_PIXELS = 800;

export const INITIAL_PROCESS_WINDOW_WIDTH_IN_PERCENTAGE = 80;

export const INITIAL_PROCESS_WINDOW_WIDTH_IN_PERCENTAGE_IF_WINDOW_LE_LIMIT = 90;

export const INITIAL_PROCESS_WINDOW_HEIGHT_IN_PERCENTAGE = 80;

export const LAST_SYSTEM_ESSENTIAL_PID = 1; 

export const INITIAL_PROCESS_WINDOW_HIGHEST_ZINDEX = 0;